name: Docker Image CI
on:
  schedule:
    - cron: 0 0 * * 1 #run every Monday 0:00
  push:
    branches:
        - master
        - 'v*'
  pull_request:
defaults:
  run:
    shell: bash
env:
  MAKEFLAGS: -j 4
jobs:
  build_bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      run: |
        set -ex
        docker build \
          --build-arg "GCC_VERSION=@7.4.0" \
          --build-arg "BASE_IMAGE=pdidevel/bionic:${image_version}" \
          -t pdidevel/bionic \
          -t pdidevel/bionic:${image_version} \
          bionic
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic
        docker push pdidevel/bionic:${image_version}
  build_gcc:
    strategy:
      matrix:
        gcc_version: ['latest', '7.4.0']
    needs: build_bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        GCC_VERSION: "${{ matrix.gcc_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "GCC_VERSION=$([ latest = "${GCC_VERSION}" ] || echo "@${GCC_VERSION}")" \
          --build-arg "BASE_IMAGE=pdidevel/bionic:${image_version}" \
          -t pdidevel/bionic_gcc-${GCC_VERSION} \
          -t pdidevel/bionic_gcc-${GCC_VERSION}:${image_version} \
          gcc
    - name: publish
      env:
        DOCKER_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
        GCC_VERSION: "${{ matrix.gcc_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_gcc-${GCC_VERSION}
        docker push pdidevel/bionic_gcc-${GCC_VERSION}:${image_version}
  build_cmake:
    strategy:
      matrix:
        gcc_version: ['latest', '7.4.0']
        cmake_version: ['latest', '3.10.2']
    needs: build_gcc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        GCC_VERSION: "${{ matrix.gcc_version }}"
        CMAKE_VERSION: "${{ matrix.cmake_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "BASE_IMAGE=pdidevel/bionic_gcc-latest:${image_version}" \
          --build-arg "CMAKE_VERSION=$([ latest = "${CMAKE_VERSION}" ] || echo "@${CMAKE_VERSION}")" \
          -t pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION} \
          -t pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}:${image_version} \
          cmake
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GCC_VERSION: "${{ matrix.gcc_version }}"
        CMAKE_VERSION: "${{ matrix.cmake_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}
        docker push pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}:${image_version}
  build_openmpi:
    strategy:
      matrix:
        gcc_version: ['latest', '7.4.0']
        cmake_version: ['latest', '3.10.2']
        openmpi_version: ['latest', '']
    needs: build_cmake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        GCC_VERSION: "${{ matrix.gcc_version }}"
        CMAKE_VERSION: "${{ matrix.cmake_version }}"
        OPENMPI_VERSION: "${{ matrix.openmpi_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "BASE_IMAGE=pdidevel/bionic_gcc-latest_cmake-3.10.2:${image_version}" \
          --build-arg "MPI=openmpi$([ latest = "${OPENMPI_VERSION}" ] || echo "@${OPENMPI_VERSION}")" \
          -t pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}_openmpi-${OPENMPI_VERSION} \
          -t pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}_openmpi-${OPENMPI_VERSION}:${image_version} \
          mpi
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        GCC_VERSION: "${{ matrix.gcc_version }}"
        CMAKE_VERSION: "${{ matrix.cmake_version }}"
        OPENMPI_VERSION: "${{ matrix.openmpi_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}_openmpi-${OPENMPI_VERSION}
        docker push pdidevel/bionic_gcc-${GCC_VERSION}_cmake-${CMAKE_VERSION}_openmpi-${OPENMPI_VERSION}:${image_version}
