name: Docker Image CI
on:
  schedule:
    - cron: 0 0 * * 1 #run every Monday 0:00
  push:
    branches:
        - master
        - 'v*'
  pull_request:
defaults:
  run:
    shell: bash
env:
  MAKEFLAGS: -j 4
jobs:
  build_bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build bionic
      run: |
        docker build -t pdidevel/bionic -t pdidevel/bionic:${image_version} bionic
  build_bionic_gcc_7_4_0:
    runs-on: ubuntu-latest
    needs: build_bionic
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build bionic/gcc@7.4.0
      run: |
        docker build --build-arg "BASE_IMAGE=pdidevel/bionic:${image_version}" --build-arg "GCC_VERSION=@7.4.0" -t pdidevel/bionic/gcc-7.4.0 -t pdidevel/gcc-7.4.0:${image_version} gcc
  build_bionic_gcc_latest:
    runs-on: ubuntu-latest
    needs: build_bionic
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build bionic/gcc@latest
      run: |
        docker build --build-arg "BASE_IMAGE=pdidevel/bionic:${image_version}" -t pdidevel/bionic/gcc-latest -t pdidevel/gcc-latest:${image_version} gcc
