name: Docker Image CI
on:
  schedule:
    - cron: 0 0 * * 1 #run every Monday 0:00
  push:
    branches:
        - master
        - 'v*'
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  step1_build_bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      run: |
        set -ex
        docker build \
          -t pdidevel/bionic \
          -t pdidevel/bionic:${image_version} \
          1-bionic
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic
        docker push pdidevel/bionic:${image_version}
  step2_build_gcc:
    strategy:
      matrix:
        gcc_version: ['11.2.0', '7.5.0']
    needs: step1_build_bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        GCC_VERSION: "${{ matrix.gcc_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "GCC_VERSION=$([ latest = "${GCC_VERSION}" ] || echo "@${GCC_VERSION}")" \
          --build-arg "BASE_IMAGE=pdidevel/bionic:${image_version}" \
          -t pdidevel/bionic_gcc-${GCC_VERSION} \
          -t pdidevel/bionic_gcc-${GCC_VERSION}:${image_version} \
          2-gcc
    - name: publish
      env:
        DOCKER_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
        GCC_VERSION: "${{ matrix.gcc_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_gcc-${GCC_VERSION}
        docker push pdidevel/bionic_gcc-${GCC_VERSION}:${image_version}
  step3_build_cmake:
    strategy:
      matrix:
        compiler:  ['gcc-latest', 'gcc-7.5.0']
        cmake_version: ['latest', '3.10.2']
    needs: step2_build_gcc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        COMPILER: "${{ matrix.compiler }}"
        CMAKE_VERSION: "${{ matrix.cmake_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "BASE_IMAGE=pdidevel/bionic_${COMPILER}:${image_version}" \
          --build-arg "CMAKE_VERSION=$([ latest = "${CMAKE_VERSION}" ] || echo "@${CMAKE_VERSION}")" \
          -t pdidevel/bionic_${COMPILER}_cmake-${CMAKE_VERSION} \
          -t pdidevel/bionic_${COMPILER}_cmake-${CMAKE_VERSION}:${image_version} \
          3-cmake
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        COMPILER: "${{ matrix.compiler }}"
        CMAKE_VERSION: "${{ matrix.cmake_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_${COMPILER}_cmake-${CMAKE_VERSION}
        docker push pdidevel/bionic_${COMPILER}_cmake-${CMAKE_VERSION}:${image_version}
  step4_build_openmpi:
    strategy:
      matrix:
        compiler:  ['gcc-latest', 'gcc-7.5.0']
        cmake: ['cmake-latest', 'cmake-3.10.2']
        openmpi_version: ['latest', '2.1.1']
    needs: step3_build_cmake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        COMPILER: "${{ matrix.compiler }}"
        CMAKE: "${{ matrix.cmake }}"
        OPENMPI_VERSION: "${{ matrix.openmpi_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "BASE_IMAGE=pdidevel/bionic_${COMPILER}_${CMAKE}:${image_version}" \
          --build-arg "MPI=openmpi$([ latest = "${OPENMPI_VERSION}" ] || echo "@${OPENMPI_VERSION}")" \
          -t pdidevel/bionic_${COMPILER}_${CMAKE}_openmpi-${OPENMPI_VERSION} \
          -t pdidevel/bionic_${COMPILER}_${CMAKE}_openmpi-${OPENMPI_VERSION}:${image_version} \
          4-mpi
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        COMPILER: "${{ matrix.compiler }}"
        CMAKE: "${{ matrix.cmake }}"
        OPENMPI_VERSION: "${{ matrix.openmpi_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_${COMPILER}_${CMAKE}_openmpi-${OPENMPI_VERSION}
        docker push pdidevel/bionic_${COMPILER}_${CMAKE}_openmpi-${OPENMPI_VERSION}:${image_version}
  step5_build_optlibs:
    strategy:
      matrix:
        compiler:  ['gcc-latest', 'gcc-7.5.0']
        cmake: ['cmake-latest', 'cmake-3.10.2']
        mpi: ['openmpi-latest', 'openmpi-2.1.1']
        optlibs_version: [ 'oldest' ]
    needs: step4_build_openmpi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        COMPILER: "${{ matrix.compiler }}"
        CMAKE: "${{ matrix.cmake }}"
        MPI: "${{ matrix.mpi }}"
        OPTLIBS_VERSION: "${{ matrix.optlibs_version }}"
      run: |
        set -ex
        docker build \
          --build-arg "BASE_IMAGE=pdidevel/bionic_${COMPILER}_${CMAKE}_${MPI}:${image_version}" \
          --build-arg "OPTLIBS_VERSION=${OPTLIBS_VERSION}" \
          -t pdidevel/bionic_${COMPILER}_${CMAKE}_${MPI}_optlibs-${OPTLIBS_VERSION} \
          -t pdidevel/bionic_${COMPILER}_${CMAKE}_${MPI}_optlibs-${OPTLIBS_VERSION}:${image_version} \
          5-optlibs
    - name: publish
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        COMPILER: "${{ matrix.compiler }}"
        CMAKE: "${{ matrix.cmake }}"
        MPI: "${{ matrix.mpi }}"
        OPTLIBS_VERSION: "${{ matrix.optlibs_version }}"
      run: |
        set -ex
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/bionic_${COMPILER}_${CMAKE}_${MPI}_optlibs-${OPTLIBS_VERSION}
        docker push pdidevel/bionic_${COMPILER}_${CMAKE}_${MPI}_optlibs-${OPTLIBS_VERSION}:${image_version}
