name: Docker Image CI
on:
  schedule:
    - cron: 0 0 * * 1 #run every Monday 0:00
  push:
    branches:
        - master
        - 'v*'
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  step1_build_base:
    permissions:
        packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build nodask
      run: |
        docker pull ghcr.io/pdidev/dockerfiles/pditst:nodask || true
        docker build --pull \
          --cache-from ghcr.io/pdidev/dockerfiles/pditst:nodask \
          -t ghcr.io/pdidev/dockerfiles/pditst:nodask \
          -t ghcr.io/pdidev/dockerfiles/pditst:nodask-${image_version} \
          -t ghcr.io/pdidev/dockerfiles/centos_libs \
          -t ghcr.io/pdidev/dockerfiles/pditst:nodask-${image_version} \
          1-bionic
    - name: publish nodask
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        set -ex
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:nodask
        docker push ghcr.io/pdidev/dockerfiles/pditst:nodask-${image_version}
    - name: build dask
      run: |
        docker pull ghcr.io/pdidev/dockerfiles/pditst:nocompiler || true
        docker build --pull \
          --cache-from ghcr.io/pdidev/dockerfiles/pditst:nocompiler \
          --build-arg "BASE_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:nodask-${image_version}" \
          -t ghcr.io/pdidev/dockerfiles/pditst:nocompiler \
          -t ghcr.io/pdidev/dockerfiles/pditst:nocompiler-${image_version} \
          2-spack
    - name: publish dask
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:nocompiler
        docker push ghcr.io/pdidev/dockerfiles/pditst:nocompiler-${image_version}
  step2_build_compiler:
    strategy:
      matrix:
        compiler: ['gcc_latest', 'gcc_7.5.0', 'clang_latest', 'clang_8.0.0']
    needs: step1_build_base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build compiler
      env:
        COMPILER: "${{ matrix.compiler }}"
      run: |
        docker pull ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs || true
        docker build --pull \
          --cache-from ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs \
          --build-arg "COMPILER=$(echo -n ${COMPILER} | sed -e s/_/@/ -e s/@latest//)" \
          --build-arg "BASE_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:nocompiler-${image_version}" \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs-${image_version} \
          3-compiler
    - name: publish compiler
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        COMPILER: "${{ matrix.compiler }}"
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs-${image_version}
    - name: build baselibs
      env:
        COMPILER: "${{ matrix.compiler }}"
      run: |
        docker pull ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi || true
        docker build --pull \
          --cache-from ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi \
          --build-arg "BASE_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nobaselibs-${image_version}" \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi-${image_version} \
          4-baselibs
    - name: publish baselibs
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        COMPILER: "${{ matrix.compiler }}"
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi-${image_version}
  step4_build_mpi:
    strategy:
      matrix:
        compiler: ['gcc_latest', 'gcc_7.5.0', 'clang_latest', 'clang_8.0.0']
        mpi:      ['openmpi_latest', 'openmpi_2.1.1']
    needs: step2_build_compiler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
      run: |
        docker pull ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI} || true
        docker build --pull \
          --cache-from ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI} \
          --build-arg "BASE_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-nompi-${image_version}" \
          --build-arg "MPI=$(echo -n ${MPI} | sed -e s/_/@/ -e s/@latest//)" \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI} \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${image_version} \
          5-mpi
    - name: publish
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${image_version}
  step5_build_libs:
    strategy:
      matrix:
        compiler:        ['gcc_latest', 'gcc_7.5.0', 'clang_latest', 'clang_8.0.0']
        mpi:             ['openmpi_latest', 'openmpi_2.1.1']
        optlibs_version: ['latest', 'oldest']
    needs: step4_build_mpi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
        OPTLIBS_VERSION: "${{ matrix.optlibs_version }}"
      run: |
        docker pull ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-libs_${OPTLIBS_VERSION} || true
        docker build --pull \
          --cache-from ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-libs_${OPTLIBS_VERSION} \
          --build-arg "BASE_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${image_version}" \
          --build-arg "OPTLIBS_VERSION=${OPTLIBS_VERSION}" \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-libs_${OPTLIBS_VERSION} \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-libs_${OPTLIBS_VERSION}-${image_version} \
          6-optlibs
    - name: publish
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
        OPTLIBS_VERSION: "${{ matrix.optlibs_version }}"
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-libs_${OPTLIBS_VERSION}
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-libs_${OPTLIBS_VERSION}-${image_version}
  step6_finalize:
    strategy:
      fail-fast: false
      matrix:
        compiler: ['gcc_latest', 'gcc_7.5.0', 'clang_latest', 'clang_8.0.0']
        mpi:      ['openmpi_latest', 'openmpi_2.1.1']
        libs:     ['', '-libs_latest', '-libs_oldest']
        cmake:    ['cmake@3.21', 'cmake@3.10']
    needs: step5_build_libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: detect current version
      run: . .github/detect_version.sh
    - name: build
      env:
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
        LIBS: "${{ matrix.libs }}"
        CMAKE: "${{ matrix.cmake }}"
      run: |
        df -h
        docker build --pull \
          --build-arg "BASE_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:nodask-${image_version}" \
          --build-arg "SPACK_IMAGE=ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}${LIBS}-${image_version}" \
          --build-arg "CMAKE=${CMAKE}" \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${CMAKE/@/_}${LIBS} \
          -t ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${CMAKE/@/_}${LIBS}-${image_version} \
          -t pdidev/pditst:${COMPILER}-${MPI}-${CMAKE/@/_}${LIBS}-${image_version} \
          7-finalize
    - name: publish
      env:
        ACTOR: "${{ github.actor }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
        LIBS: "${{ matrix.libs }}"
        CMAKE: "${{ matrix.cmake }}"
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${ACTOR} --password-stdin
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${CMAKE/@/_}${LIBS}
        docker push ghcr.io/pdidev/dockerfiles/pditst:${COMPILER}-${MPI}-${CMAKE/@/_}${LIBS}-${image_version}
    - name: public publish
      if: "${{ github.event_name == 'push' }}"
      env:
        DOCKER_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
        COMPILER: "${{ matrix.compiler }}"
        MPI: "${{ matrix.mpi }}"
        LIBS: "${{ matrix.libs }}"
        CMAKE: "${{ matrix.cmake }}"
      run: |
        echo ${DOCKER_TOKEN} | docker login -u jbigot --password-stdin
        docker push pdidev/pditst:${COMPILER}-${MPI}-${CMAKE/@/_}${LIBS}-${image_version}
