name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: centos_base Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: pdidev/dockerfiles/centos_base
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: centos_base
    - name: centos_cmake3.5 Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: pdidev/dockerfiles/centos_cmake3.5
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: centos_cmake3.5
    - name: centos_cmake3.10 Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: pdidev/dockerfiles/centos_cmake3.10
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: centos_cmake3.10
    - name: centos_libs Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: pdidev/dockerfiles/centos_libs
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: centos_libs
    - name: centos_libs_cmake3.5 Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: pdidev/dockerfiles/centos_libs_cmake3.5
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: centos_libs_cmake3.5
    - name: centos_libs_cmake3.10 Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.13
      with:
        name: pdidev/dockerfiles/centos_libs_cmake3.10
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: centos_libs_cmake3.10
