name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
env:
  MAKEFLAGS: -j 4
jobs:
  build_xenial:
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
       python-version: '3.9'
    - name: Setup python deps
      run: |
        python3 -m pip install PyYAML
    - uses: actions/checkout@v2
    - name: checkout PDI master
      run: |
        git clone https://gitlab.maisondelasimulation.fr/pdidev/pdi.git pdi_repo
    - name: build xenial_cmake3.5
      run: |
        docker build -t pdidevel/xenial_cmake3.5 xenial_cmake3.5
    - name: test xenial_cmake3.5
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github xenial_cmake3.5_embedded
    - name: build xenial_cmake3.10
      run: |
        docker build -t pdidevel/xenial_cmake3.10 xenial_cmake3.10
    - name: test xenial_cmake3.10
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github xenial_cmake3.10_embedded
    - name: build xenial_libs_cmake3.5
      run: |
        docker build -t pdidevel/xenial_libs_cmake3.5 xenial_libs_cmake3.5
    - name: test xenial_libs_cmake3.5
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github xenial_cmake3.5_system
    - name: build xenial_libs_cmake3.10
      run: |
        docker build -t pdidevel/xenial_libs_cmake3.10 xenial_libs_cmake3.10
    - name: test xenial_libs_cmake3.10
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github xenial_cmake3.10_system
    - name: build xenial_pdi
      run: |
        cp -la pdi_repo xenial_pdi/
        docker build -t pdidevel/xenial_pdi xenial_pdi
    - name: publish
      if: ${{ github.event_name == 'push' }}
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/xenial_cmake3.5
        docker push pdidevel/xenial_cmake3.10
        docker push pdidevel/xenial_libs_cmake3.5
        docker push pdidevel/xenial_libs_cmake3.10
        docker push pdidevel/xenial_pdi
  build_centos:
    runs-on: ubuntu-latest
    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
       python-version: '3.9'
    - name: Setup python deps
      run: |
        python3 -m pip install PyYAML
    - uses: actions/checkout@v2
    - name: checkout PDI master
      run: |
        git clone https://gitlab.maisondelasimulation.fr/pdidev/pdi.git pdi_repo
    - name: build centos_base
      run: |
        docker build -t pdidevel/centos_base centos_base
    - name: build centos_cmake3.5
      run: |
        docker build -t pdidevel/centos_cmake3.5 centos_cmake3.5
    - name: test centos_cmake3.5
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github centos_cmake3.5_embedded
    - name: build centos_cmake3.10
      run: |
        docker build -t pdidevel/centos_cmake3.10 centos_cmake3.10
    - name: test centos_cmake3.10
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github centos_cmake3.10_embedded
    - name: build centos_libs_cmake3.10
      run: |
        docker build -t pdidevel/centos_libs_cmake3.10 centos_libs_cmake3.10
    - name: test centos_libs_cmake3.10
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github centos_cmake3.10_system
    - name: build centos_libs_cmake3.5
      run: |
        docker build -t pdidevel/centos_libs_cmake3.5 centos_libs_cmake3.5
    - name: test centos_libs_cmake3.5
      run: |
        ./pdi_repo/tools/build_scripts/test_in_docker github centos_cmake3.5_system
    - name: publish
      if: ${{ github.event_name == 'push' }}
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/centos_base
        docker push pdidevel/centos_cmake3.5
        docker push pdidevel/centos_cmake3.10
        docker push pdidevel/centos_libs_cmake3.10
        docker push pdidevel/centos_libs_cmake3.5
