name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
env:
  MAKEFLAGS: -j 5
jobs:
  build_xenial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout PDI master
      run: |
        git clone https://gitlab.maisondelasimulation.fr/pdidev/pdi.git pdi_repo
    - name: build xenial_cmake3.5
      run: |
        docker build -t pdidevel/xenial_cmake3.5 xenial_cmake3.5
    - name: test xenial_cmake3.5
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/xenial_cmake3.5 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build xenial_cmake3.10
      run: |
        docker build -t pdidevel/xenial_cmake3.10 xenial_cmake3.10
    - name: test xenial_cmake3.10
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/xenial_cmake3.10 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build xenial_libs_cmake3.5
      run: |
        docker build -t pdidevel/xenial_libs_cmake3.5 xenial_libs_cmake3.5
    - name: test xenial_libs_cmake3.5
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/xenial_libs_cmake3.5 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build xenial_libs_cmake3.10
      run: |
        docker build -t pdidevel/xenial_libs_cmake3.10 xenial_libs_cmake3.10
    - name: test xenial_libs_cmake3.10
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/xenial_libs_cmake3.10 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build xenial_pdi
      run: |
        cp -la pdi_repo xenial_pdi/
        docker build -t pdidevel/xenial_pdi xenial_pdi
    - name: build pdi_tutorial
      run: |
        docker build -t pdidevel/pdi_tutorial pdi_tutorial
    - name: publish
      if: ${{ github.event_name == 'push' }}
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/xenial_cmake3.5
        docker push pdidevel/xenial_cmake3.10
        docker push pdidevel/xenial_libs_cmake3.5
        docker push pdidevel/xenial_libs_cmake3.10
        docker push pdidevel/xenial_pdi
        docker push pdidevel/pdi_tutorial
  build_centos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: checkout PDI master
      run: |
        git clone https://gitlab.maisondelasimulation.fr/pdidev/pdi.git pdi_repo
    - name: build centos_base
      run: |
        docker build -t pdidevel/centos_base centos_base
    - name: build centos_cmake3.5
      run: |
        docker build -t pdidevel/centos_cmake3.5 centos_cmake3.5
    - name: test centos_cmake3.5
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/centos_cmake3.5 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build centos_cmake3.10
      run: |
        docker build -t pdidevel/centos_cmake3.10 centos_cmake3.10
    - name: test centos_cmake3.10
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/centos_cmake3.10 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build centos_libs_cmake3.10
      run: |
        docker build -t pdidevel/centos_libs_cmake3.10 centos_libs_cmake3.10
    - name: test centos_libs_cmake3.10
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/centos_libs_cmake3.10 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
             && sh tools/build_scripts/build_and_run.sh"
    - name: build centos_libs_cmake3.5
      run: |
        docker build -t pdidevel/centos_libs_cmake3.5 centos_libs_cmake3.5
    - name: test centos_libs_cmake3.5
      run: |
        docker run -e DOCKER_RUNNER=github -t -v $PWD/pdi_repo:/data/ pdidevel/centos_libs_cmake3.5 /bin/bash -c \
            "mkdir /tmp/pdi_repo && cp -a /data/ /tmp/pdi_repo && cd /tmp/pdi_repo/data/ \
            && sh tools/build_scripts/build_and_run.sh"
    - name: publish
      if: ${{ github.event_name == 'push' }}
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u jbigot -p "${DOCKER_TOKEN}"
        docker push pdidevel/centos_base
        docker push pdidevel/centos_cmake3.5
        docker push pdidevel/centos_cmake3.10
        docker push pdidevel/centos_libs_cmake3.10
        docker push pdidevel/centos_libs_cmake3.5
